import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { AccountSearch } from "./account-search";
import { rankPublicHunts } from "@/lib/domain/public-social";
import { useAuth } from "@/lib/hooks/use-auth";
import { useSocial } from "@/lib/hooks/use-social";
import { formatScore } from "@/lib/ui/format-score";

export function SocialLeaderboard() { const { user } = useAuth(); const { hunts, followingIds, toggleFollow, loading, error } = useSocial(); const species = useMemo(() => [...new Set(hunts.filter((hunt) => hunt.measurement?.score).map((hunt) => hunt.species))], [hunts]); const [selected, setSelected] = useState<string | null>(null); const active = selected && species.includes(selected) ? selected : species[0]; const ranked = active ? rankPublicHunts(hunts, active) : []; if (!user) return null; return <section className="lb-view"><header className="lb-header"><p className="lb-season">PUBLIC COMMUNITY · PUBLISHED RECORDS</p><h1 className="lb-title">Leaderboard</h1><p className="lb-intro">Find hunters, follow their portfolios, and compare published factual scores.</p><AccountSearch currentUserId={user.uid} followingIds={followingIds} onToggleFollow={toggleFollow} /></header>{error ? <p role="alert">{error}</p> : null}{loading ? <div className="lb-empty">Loading public rankings…</div> : species.length === 0 ? <div className="lb-empty"><h2>No published scores yet</h2><p>Published measured hunts will appear here.</p></div> : <><div className="lb-species-scroll">{species.map((item) => <button key={item} type="button" className={`lb-species-pill${item === active ? " lb-species-active" : ""}`} onClick={() => setSelected(item)}>{item}</button>)}</div><div className="lb-list-wrap"><div className="lb-list">{ranked.map((hunt, index) => <Link className={`lb-row${index === 0 ? " lb-row-first" : ""}`} key={hunt.id} to={`/people/${hunt.ownerId}/hunts/${hunt.id}`}><span className="lb-rank">{String(index + 1).padStart(2, "0")}</span><span className="lb-row-info"><strong>{hunt.hunter.displayName}</strong><span>{hunt.location.farmName || hunt.location.placeName} · {hunt.country}</span></span><span className="lb-row-score">{typeof hunt.measurement?.score === "number" ? formatScore(hunt.measurement.score, hunt.measurement.scoreUnit) : "—"}</span></Link>)}</div></div></>}</section>; }
